"""empty message

Revision ID: 052cd9e035d2
Revises: 944f3122f51e
Create Date: 2022-11-07 12:58:26.596375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052cd9e035d2'
down_revision = '944f3122f51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('disabled', sa.Boolean(), nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'disabled')
    # ### end Alembic commands ###