"""empty message

Revision ID: 944f3122f51e
Revises: fabf2ca39860
Create Date: 2022-08-12 13:44:41.398334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944f3122f51e'
down_revision = 'fabf2ca39860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'devices', ['label'])
    op.create_unique_constraint(None, 'templates', ['label'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    # ### end Alembic commands ###